version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" # Change host port to 5673 to avoid conflict
      - "15673:15672" # Change management UI port to 15673 to avoid conflict
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      /bin/bash -c "
      rabbitmq-server -detached;
      rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbitmq.pid;
      rabbitmqctl add_vhost celeryvhost;
      rabbitmqctl add_user celery celery;
      rabbitmqctl set_user_tags celery administrator;
      rabbitmqctl set_permissions -p celeryvhost celery '.*' '.*' '.*';
      rabbitmqctl stop;
      rabbitmq-server"

 
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    image: smart-canteen
    # volumes:
    #   - ./canteen:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DEBUG=1
    env_file:
      - ./canteen/.env

volumes:
  rabbitmq_data: