


version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" 
      - "15673:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      /bin/bash -c "
      rabbitmq-server -detached;
      rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbitmq.pid;
      rabbitmqctl add_vhost celeryvhost;
      rabbitmqctl add_user celery celery;
      rabbitmqctl set_user_tags celery administrator;
      rabbitmqctl set_permissions -p celeryvhost celery '.*' '.*' '.*';
      rabbitmqctl stop;
      rabbitmq-server"

  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    image: smart-canteen
    volumes:
      - media_data:/app/media/
      - db_data:/app/db/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DEBUG=1

  celery:
    # build: .
    image: smart-canteen
    command: poetry run celery -A core worker --loglevel=info
    volumes:
      - media_data:/app/media/
      - db_data:/app/db/
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://celery:celery@rabbitmq:5672/celeryvhost
      - CELERY_RESULT_BACKEND=rpc://

volumes:
  rabbitmq_data:
  media_data:
  db_data: