# Generated by Django 5.0.6 on 2024-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menu_items', to='base.fooditem'),
        ),
    ]
