# Generated by Django 5.0.6 on 2024-05-19 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_userprofile_administration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.AlterModelOptions(
            name='menuschedule',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='menuschedule',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
