# Generated by Django 5.0.6 on 2024-05-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_breaktime_course_alter_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='FoodItem',
        ),
        migrations.RenameModel(
            old_name='MenuSchedule',
            new_name='Menu',
        ),
    ]
