# Generated by Django 5.0.6 on 2024-05-19 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_order_orders_alter_menuschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
