# Generated by Django 5.0.6 on 2024-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orders_order_time_orders_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaktime',
            options={'ordering': ['semester'], 'verbose_name': 'Break Time', 'verbose_name_plural': 'Break Times'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='menu_items',
            field=models.ManyToManyField(related_name='menu_items', to='base.menuitem'),
        ),
    ]
