# Generated by Django 5.0.6 on 2024-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_options_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college_id',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
