# Generated by Django 5.0.6 on 2024-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_college_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['college_id']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college_id',
            field=models.IntegerField(unique=True),
        ),
    ]
